### consultar todas las peliculas
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJhbHVtbm8xIiwiaWF0IjoxNzc1ODczMjY3LCJleHAiOjE3NzU5MDkyNjd9.Lr0f4hCfFktav2DtJyOJC-GI8RuzpnA85ZCPtmEOw-Y

### login de usuario 
POST http://localhost:3000/auth/login
Content-Type:   application/json

{
    "username": "alumno1",
    "password": "hash_falso_456"
}

### consultar una pelicula por id o general
GET http://localhost:3000/movies?year=2003
Authorization:  Bearer {{token}}
Content-Type:   application/json

### crear
POST http://localhost:3000/movies
Authorization:  Bearer {{token}}
Content-Type:   application/json

{
    "title": "Donde están las rubias",
    "release_year": 2003,
    "synopsis": "Pelicula de comedia.",
    "genre": [1, 2],
    "director": [2, 4],
    "poster_url": "https://m.media-amazon.com/images/I/51EG732BV3L.jpg"
}

### actualizar
PUT http://localhost:3000/movies/6
Authorization: Bearer {{token}}
Content-Type:   application/json

{
    "title": "Las locas rubias",
    "director": [1]
}

### eliminar un recurso
DELETE http://localhost:3000/movies/5
Authorization: Bearer {{token}}
Content-Type:   application/json


### consultar todos los generos
GET http://localhost:3000/genres/
Authorization: Bearer {{token}}
Content-Type:   application/json

### consultar un genero por id o general
GET http://localhost:3000/genres/1
Authorization: Bearer {{token}}
Content-Type:   application/json

### crear un genero
POST http://localhost:3000/genres
Authorization: Bearer {{token}}
Content-Type:   application/json

{
    "name": "Comedia"
}

### actualizar un genero
PUT http://localhost:3000/genres/6
Authorization: Bearer {{token}}
Content-Type:   application/json

{
    "name": "Comedia Romantica"
}

### eliminar un genero
DELETE http://localhost:3000/genres/6
Authorization: Bearer {{token}}
Content-Type:   application/json


### consultar todos los directores
GET http://localhost:3000/directors
Authorization: Bearer {{token}}
Content-Type:   application/json

### consultar un director por id o general
GET http://localhost:3000/directors/1
Authorization: Bearer {{token}} 
Content-Type:   application/json

### crear un director
POST http://localhost:3000/directors
Authorization: Bearer {{token}}
Content-Type:   application/json

{
    "name": "Steven Spielberg"
}

### actualizar un director
PUT http://localhost:3000/directors/5
Authorization: Bearer {{token}}
Content-Type:   application/json
{
    "name": "Leonardo Amaya "
}

### eliminar un director
DELETE http://localhost:3000/directors/6
Authorization: Bearer {{token}}
Content-Type:   application/json


